version: "3.9"
services:
 db:
  image: postgres:14
  restart: always
  environment:
   - POSTGRES_USER=user
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=db
  ports:
   - "5432:5432"
  volumes:
   - ./db_data:/var/lib/postgresql/data

 api:
  build: .
  ports:
   - "8000:8000"
  depends_on:
   - db
  environment:
   - DATABASE_URL=postgresql://user:password@db:5432/db